### ISSUE TITLE
Why is original UID not used?

### ISSUE THREAD

**Issue by rjhorniii** [PuloV/ics-golang#16]
This is just a question.  Why is a new UID generated for every event?  The original ID is also preserved, so I've got no problem with this.  I am just curious why it was needed.

**Comment by buildscientist** [comment]
@PuloV can probably speak to this better but there is no way of guaranteeing that the ICS file being parsed has events with original IDs that are _actually_ unique. 

Have a look at [RFC5545](https://tools.ietf.org/html/rfc5545) - specifically the [section](https://tools.ietf.org/html/rfc5545#section-3.8.4.7) of UIDs. 

I have personally seen cases (Google Calendar exports) where a UID is re-used with a modified event that has an identical start/end time - but different summary,location and description.

**Comment by buildscientist** [comment]
@PuloV recommend we close this one out and label as a question.
