### ISSUE TITLE
Add option to not use local files

### ISSUE THREAD

**Issue by bakito** [PuloV/ics-golang#17]
I'd like to use this library in an environment, where I'm not allowed to write any tmp files. My application runs in a docker FROM scratch container.

It would be nice if the library supported a mode where the ics file is not saved into a local file.

**Comment by buildscientist** [comment]
@bakito can you clarify your use case? Are you saying if the library is used to grab the ICS over http - the file shouldn't be saved to disk?

@PuloV Recommend marking as an enhancement/feature request. Biggest concern here is holding the request.body in memory while various calendar maps are being generated. Not sure how fancy we want to get with this but we may want to consider using a [memory map](https://godoc.org/golang.org/x/exp/mmap) for large files.

**Comment by bakito** [comment]
Correct. Since I'm running the go binary I don't have permissions to write the files.

what if the ics files would be downloaded into a []byte instead of a file in downloadFromUrl?

**Comment by buildscientist** [comment]
@bakito that's possible but as I said previously some of these ICS files can get rather large. 

So in addition to the lists/maps ics-golang is maintaining in memory - now there is a byte buffer as well. Not a big issue if you're processing a small number of files. 

When/if that grows the amount of memory your golang binary uses is also going to grow. We could force garbage collection but now we're complicating the library even further.

**Comment by buildscientist** [comment]
@bakito - looks like @leosunmo has a []byte implementation in his fork of ics-golang see 9cf6ac9182a429be404ec8a2d1b24f3507714ff6 for more details. 

Note his change completely removes persisting the ics file to disk. Not the approach I would take with this. At the very least it the developer should have the option of storing in a []byte or writing a temp file to disk.

**Comment by buildscientist** [comment]
/cc @PuloV 

@leosunmo feel free to submit a PR for this feature but I'd ask that you leave existing functionality of persisting the ics file to disk in place. Removing this functionality breaks the API - leaving existing users in a bit of a lurch.

I would add another bool to [utils.go](https://github.com/PuloV/ics-golang/blob/master/utils.go) that allows the developer to opt in/out of saving to disk. Ideally the boolean values in utils.go would be refactored such that they're passed to the constructor of ics - 

e.g. ` parser := ics.New(saveToDisk,deleteTempFile)`

**Comment by bakito** [comment]
> @bakito - looks like @leosunmo has a []byte implementation in his fork of ics-golang see [9cf6ac9](https://github.com/PuloV/ics-golang/commit/9cf6ac9182a429be404ec8a2d1b24f3507714ff6) for more details.
> 
> Note his change completely removes persisting the ics file to disk. Not the approach I would take with this. At the very least it the developer should have the option of storing in a []byte or writing a temp file to disk.

This would be fine for me.
