### ISSUE TITLE
Active Repo?

### ISSUE THREAD

**Issue by buildscientist** [PuloV/ics-golang#26]
Hello @PuloV - is this repo still active? There are 10 PR's and I was wondering if you could give someone write access to this repo to merge the PR's into. 

Thanks.

**Comment by PuloV** [comment]
Hi @buildscientist 
Thanks for your support.
I'm trying to be active.
If you want to close/merge PRs, please go and leave review/comments and then ping me.

**Comment by buildscientist** [comment]
Thanks - will do. Is there any chance we can get CI around the PR's? At least that way we can determine if the PR breaks existing tests?

**Comment by buildscientist** [comment]
I can setup CircleCI - they are very generous with free compute cycles for open source projects.

**Comment by PuloV** [comment]
Can you setup the `.circleci/config.yml` ? I'll try later today to setup it.
Will let you know about the results

**Comment by buildscientist** [comment]
Closing as this was merged by PR #27
